### ISSUE TITLE
Variable card.querySelector not working

### ISSUE THREAD

**Issue by Schmu1605** [Clooos/Bubble#4]
if I try ${card.querySelector('.bubble-name').innerText = "It's currently " +
hass.states['weather.home'].state} like the example or anything other with card.querySelector, it shows 
"Cant´t find variable card" on the bubble card.
What is wrong or missing?
Please help

**Comment by Clooos** [comment]
Hi, can you tell me on what card you are using this template? Can you also share your YAML?

**Comment by Schmu1605** [comment]
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    name: ''
    icon: ''
    sub_button:
      - entity: sensor.temp_sensor_wohnzimmer_temperature
        icon: null
        show_state: true
        tap_action:
          action: none
        show_background: false
        show_attribute: false
        show_last_changed: false
        show_name: false
      - entity: binary_sensor.presence_sensor_fp2_d042_presence_sensor_1
        show_state: true
        icon: mdi:table-furniture
        show_background: true
      - entity: weather.forecast_home_forecast
        show_icon: true
        show_name: false
        show_state: true
        show_last_changed: false
        show_attribute: true
        attribute: temperature
    styles: |-
      ${card.querySelector('.bubble-name').innerText = "It's currently " +
      hass.states['weather.home_2'].state}
    card_layout: normal
    entity: sensor.openweathermap_temperature
    scrolling_effect: false
    show_name: false
    show_attribute: true

**Comment by Schmu1605** [comment]
<img width="602" alt="Bildschirmfoto 2024-08-04 um 21 05 53" src="https://github.com/user-attachments/assets/5e8c04b0-ec8f-4e46-bc2d-fcf67987000e">

**Comment by Clooos** [comment]
Thank you, I don't understand why it's not working but I will take a look at that soon.

**Comment by Schmu1605** [comment]
thx

**Comment by Schmu1605** [comment]
do you know what is wrong and how to solve?

**Comment by Schmu1605** [comment]
SORRY I FOUND THE BUG
i had a old manuell install of bubble card - so I deleted all installed with hacs - NOW IT WORKS PERFECT
